forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/ntp',        '11.1.0'
mod 'puppetlabs/haproxy',     '8.2.0'
mod 'puppetlabs/stdlib',      '9.7.0'
mod 'puppetlabs/concat',      '9.1.0'
mod 'puppetlabs/puppetdb',    '8.1.0'
mod 'puppetlabs/postgresql', '10.6.1'
mod 'puppetlabs/firewall',    '8.3.0'
mod 'puppetlabs/inifile',     '6.3.0'
mod 'puppetlabs/apt',        '11.2.0'
mod 'theforeman/puppet',     '22.1.0'
mod 'puppet/extlib',          '7.5.1'
mod 'puppet/systemd',         '9.4.0'
mod 'puppetlabs/postgresql', '10.6.1'
